# Travis CI template generic mkdocs sites with GitHub pages deployments

# Use a specific Ubuntu distro
dist: xenial
# We are going to use Python 3.7
language: python
python:
  - 3.7

# Install mkdocs and mkdocs-material
install:
  - pip install -U mkdocs
  - pip install -U mkdocs-material

# Build the site with mkdocs
script:
  - python -m mkdocs build --clean

# Finally, deploy to GitHub pages
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: "site/"
  fqdn: $GITHUB_DOMAIN
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
