# The name of the site
# Change this
site_name: "DumpsterDiving"

# Navigation information
# Also change this
nav:
  - Home: "index.md"
  - Install: "install.md"
  - Configuration: "config.md"

# The theme and the colors of it
theme:
  name: material
  palette:
    primary: red
    accent: red

# Social Network links at the bottom of the page
extra:
  social:
    - type: discord
      link: "https://discord.gg/Cf6sspj"
    - type: github
      link: "https://github.com/justalemon"
    - type: steam
      link: "https://steamcommunity.com/profiles/76561198118215221/"
    - type: twitter
      link: "https://twitter.com/justlemonades"
    - type: twitch
      link: "https://www.twitch.tv/justlemoncl"
    - type: gamepad
      link: "https://www.gta5-mods.com/users/justalemon"
